#!/bin/bash
#
#To enable this hook, move the file to .git/hooks
echo $(dirname $0)

PROJECTPATH=$(cd `dirname $0`;pwd)

args=$(git diff-index --name-only HEAD)

PYTHON_CODE_STYLE_DIR="python_code_style"

python $PROJECTPATH/../../$PYTHON_CODE_STYLE_DIR/localhooks/pre_commit.py $args

if [ $? -ne 0 ];then
	exit 1
else
	exit 0
fi